---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pgsql-account
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: add-secrets
  namespace: default
rules:
  - apiGroups: [""]
    resources:
      - secrets
      - pods
    verbs:
      - get
      - list
      - create
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: modify-pods-to-sa
subjects:
  - kind: ServiceAccount
    name: pgsql-account
roleRef:
  kind: Role
  name: add-secrets
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: pgsql
  labels:
    app: pgsql
spec:
  selector:
    app: pgsql
  ports:
    - port: 5432
      name: pgsql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgsql
  labels:
    app: pgsql
  namespace: default
spec:
  selector:
    matchLabels:
      app: pgsql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pgsql
    spec:
      securityContext:
        fsGroup: 1000
      serviceAccountName: pgsql-account
      containers:
        - image: eu-zurich-1.ocir.io/zrubfvj5fjty/pgsql:13
          imagePullPolicy: Always
          name: pgsql
          env:
            - name: PG_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: pgsql-admin
                  key: username
            - name: PG_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgsql-admin
                  key: password
          ports:
            - containerPort: 5432
              name: pgsql
          volumeMounts:
            - name: pglib-persistent-storage
              mountPath: /var/lib/postgresql
          resources:
            requests:
              cpu: 1000m
              memory: 1000M
            limits:
              cpu: 2000m
              memory: 2000M
      volumes:
        - name: pglib-persistent-storage
          persistentVolumeClaim:
            claimName: pg-local-claim
      imagePullSecrets:
        - name: ociregistry
