- name: Create instance in GCP

  hosts: localhost
  connection: local

  vars:
    gcp_cred_kind: serviceaccount
    gcp_svc_file: ~/.gcp_svc_tutogc.json
    gcp_project: tutogc
    gcp_region: europe-west4
    gcp_zone: europe-west4-c

  tasks:
    - name: Create a disk
      google.cloud.gcp_compute_disk:
        name: immotep-disk1
        size_gb: 50
        source_image: projects/ubuntu-os-cloud/global/images/family/ubuntu-2404-lts-amd64
        type: hyperdisk-balanced
        zone: "{{ gcp_zone }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_svc_file }}"
        state: present
      register: disk

    - name: Create a network
      google.cloud.gcp_compute_network:
        name: immotep-network
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_svc_file }}"
        state: present
        auto_create_subnetworks: true
      register: network

    - name: Create firewall rules for ssh/http/https
      google.cloud.gcp_compute_firewall:
        name: immotep-fw-rules
        allowed:
          - ip_protocol: tcp
            ports:
              - '22'
              - '80'
              - '443'
        network: "{{ network }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_svc_file }}"
        state: present

    - name: Create a address
      google.cloud.gcp_compute_address:
        name: immotep-ext-address
        region: "{{ gcp_region }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_svc_file }}"
        state: present
      register: address

    - name: Create a instance
      google.cloud.gcp_compute_instance:
        name: immotep-vm
        machine_type: "n4-standard-4"
        disks:
          - auto_delete: 'true'
            boot: 'true'
            source: "{{ disk }}"
        labels:
          environment: production
        network_interfaces:
          - network: "{{ network }}"
            access_configs:
              - name: External NAT
                nat_ip: "{{ address }}"
                type: ONE_TO_ONE_NAT
        zone: "{{ gcp_zone }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_svc_file }}"
        state: present

    - name: Generate inventory
      ansible.builtin.template:
        src: ./gcpinv.ini.j2
        mode: '644'
        dest: ./gcpinv.ini

    - name: Create a bucket
      google.cloud.gcp_storage_bucket:
        name: immotep-storage
        location: europe-west9
        storage_class: STANDARD
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_svc_file }}"
        state: present
