- name: Create instance in GCP

  hosts: localhost
  connection: local

  vars:
    gcp_cred_kind: serviceaccount
    gcp_svc_file: ~/.gcp_svc_tutogc.json
    gcp_project: tutogc
    gcp_region: europe-west4
    gcp_zone: europe-west4-c

  tasks:
    - name: Delete a instance
      google.cloud.gcp_compute_instance:
        name: immotep-vm
        zone: "{{ gcp_zone }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_svc_file }}"
        state: absent

    - name: Delete a disk
      google.cloud.gcp_compute_disk:
        name: immotep-disk1
        zone: "{{ gcp_zone }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_svc_file }}"
        state: absent

    - name: Delete firewall rules for ssh/http/https
      google.cloud.gcp_compute_firewall:
        name: immotep-fw-rules
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_svc_file }}"
        state: absent

    - name: Delete a address
      google.cloud.gcp_compute_address:
        name: immotep-ext-address
        region: "{{ gcp_region }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_svc_file }}"
        state: absent
      register: address

    - name: Delete a network
      google.cloud.gcp_compute_network:
        name: immotep-network
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_svc_file }}"
        state: absent
